### ISSUE TITLE
data를 컨트롤러에서 리턴하면 CommonResponse를 자동으로 만들어주는 기능 없나요?

### ISSUE THREAD

**Issue by ChoiWheatley** [coding-jjun/wishlist_funding_backend#17]
#14 를 진행하는 와중에 컨트롤러의 메서드가 `CommonResponse`를 리턴하고, 그것을 만족하기 위하여 매번 새 JS 객체를 만들어 리턴하고 있었습니다. 코드가 반복이 되는 것 같아서 컨트롤러와 직렬화 중간에 어떤 미들웨어를 만들어 자동으로 timestamp, message를  만들어 리턴하도록 하면 좋을 것 같아 이슈 남깁니다.

**Comment by coding-jjun** [comment]
찾아보니까 미들웨어는 요청이 컨트롤러로 전달되기 전에만 실행될 수 있는 함수이고 인터셉터는 요청이 컨트롤러에 전달된 후에도 실행될 수 있더라고요.
TransformInterceptor 사용하면 컨트롤러의 메서드는 data만 반환하고 인터셉터가 그 data를 CommonResponse 넣어서 반환하도록 설정 가능한 것 같습니다.
지금 exception-filter랑 로깅을 위한 미들웨어 작업 중인데 이것도 반영해두겠습니다.
